/**
 * Traceback file parser and Sentry event builder for `sentry bash-hook --send-event`.
 *
 * The generated bash script writes a traceback file with one frame per line
 * in `function:file:line` format, followed by metadata lines prefixed with `@`.
 * This module parses that format and constructs a Sentry event with a
 * BashError exception, stack trace with source context, and optional
 * log-file breadcrumbs.
 */

import { readFile } from "node:fs/promises";
import type { Breadcrumb, Event, StackFrame } from "@sentry/core";
import { uuid4 } from "@sentry/core";
import { ValidationError } from "../errors.js";
import { logger } from "../logger.js";

const log = logger.withTag("bash-hook.traceback");

/** Maximum number of log-file lines to attach as breadcrumbs. */
const MAX_BREADCRUMBS = 100;

/**
 * Regex matching a stack frame line: `function:file:line`.
 *
 * Uses non-greedy match on the function name segment so that file paths
 * containing colons (e.g., `C:\Users\...`) are captured correctly. This
 * is safe because bash function names cannot contain colons.
 */
const FRAME_RE = /^(.*?):(.*):(\d+)$/;

/** Internal function names generated by the bash hook — filtered from stack traces. */
const INTERNAL_FRAMES = new Set([
  "_sentry_err_trap",
  "_sentry_exit_trap",
  "_sentry_traceback",
]);

/**
 * Parsed metadata and stack frames extracted from a bash-hook traceback file.
 *
 * @internal Exported for testing
 */
export type TracebackData = {
  /** The shell command that triggered the error. */
  command: string;
  /** The exit code of the failing command. */
  exitCode: number;
  /** Stack frames as read from the traceback file (innermost/callee first). */
  frames: StackFrame[];
};

/**
 * Parse a single line from the traceback file into a stack frame, or return
 * null if the line is not a valid frame (metadata, blank, or internal hook).
 */
function parseFrameLine(line: string): StackFrame | null {
  const match = FRAME_RE.exec(line);
  if (!match) {
    return null;
  }

  const funcName = match[1] ?? "";
  if (INTERNAL_FRAMES.has(funcName)) {
    return null;
  }

  return {
    function: funcName || undefined,
    filename: match[2],
    lineno: Number.parseInt(match[3] ?? "0", 10) || undefined,
  };
}

/**
 * Parse a bash-hook traceback file into structured data.
 *
 * The file format is one frame per line as `function:file:line`, followed
 * by metadata lines `@command:<cmd>` and `@exit_code:<code>`. Internal
 * hook frames (_sentry_err_trap, etc.) are filtered out.
 *
 * @internal Exported for testing
 */
export function parseTracebackContent(content: string): TracebackData {
  let command = "unknown";
  let exitCode = 1;
  const frames: StackFrame[] = [];

  for (const line of content.split("\n")) {
    if (!line) {
      continue;
    }

    // Metadata lines
    if (line.startsWith("@command:")) {
      command = line.slice("@command:".length);
      continue;
    }
    if (line.startsWith("@exit_code:")) {
      const parsed = Number.parseInt(line.slice("@exit_code:".length), 10);
      if (Number.isFinite(parsed)) {
        exitCode = parsed;
      }
      continue;
    }
    if (line.startsWith("@")) {
      continue;
    }

    const frame = parseFrameLine(line);
    if (frame) {
      frames.push(frame);
    }
  }

  return { command, exitCode, frames };
}

/**
 * Enrich stack frames with source context from the original files.
 *
 * Reads each frame's source file and attaches ±5 lines of context around
 * the error line. File contents are cached to avoid redundant reads.
 */
async function enrichFramesWithSourceContext(
  frames: StackFrame[]
): Promise<void> {
  const sourceCache = new Map<string, string[] | null>();

  for (const frame of frames) {
    if (!(frame.filename && frame.lineno)) {
      continue;
    }

    let lines = sourceCache.get(frame.filename);
    if (lines === undefined) {
      try {
        const content = await readFile(frame.filename, "utf-8");
        lines = content.split("\n");
      } catch (err) {
        log.debug(`Could not read source file ${frame.filename}`, err);
        lines = null;
      }
      sourceCache.set(frame.filename, lines);
    }

    if (!lines) {
      continue;
    }

    const idx = frame.lineno - 1;
    frame.context_line = lines[idx];
    frame.pre_context = lines.slice(Math.max(0, idx - 5), idx);
    frame.post_context = lines.slice(idx + 1, Math.min(idx + 6, lines.length));
  }
}

/**
 * Parse a log file into breadcrumbs for the Sentry event.
 *
 * Each non-empty line becomes a breadcrumb with category "log".
 * Only the last {@link MAX_BREADCRUMBS} lines are kept.
 */
async function parseLogBreadcrumbs(logPath: string): Promise<Breadcrumb[]> {
  let content: string;
  try {
    content = await readFile(logPath, "utf-8");
  } catch (err) {
    log.debug(`Could not read log file ${logPath}`, err);
    return [];
  }

  const lines = content.split("\n").filter((l) => l.length > 0);
  const timestamp = Date.now() / 1000;
  const breadcrumbs: Breadcrumb[] = lines.map((line) => ({
    timestamp,
    category: "log",
    message: line,
  }));

  if (breadcrumbs.length > MAX_BREADCRUMBS) {
    return breadcrumbs.slice(-MAX_BREADCRUMBS);
  }
  return breadcrumbs;
}

/**
 * Build a Sentry event from a bash-hook traceback file and optional log file.
 *
 * Parses the traceback file for stack frames and metadata, enriches frames
 * with source context, reverses to Sentry's oldest-to-youngest order, and
 * attaches log-file breadcrumbs. The resulting event has exception type
 * "BashError" with a full stack trace.
 */
export async function buildBashErrorEvent(opts: {
  tracebackPath: string;
  logPath?: string;
  tags?: Record<string, string>;
  release?: string;
}): Promise<Event> {
  let tracebackContent: string;
  try {
    tracebackContent = await readFile(opts.tracebackPath, "utf-8");
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code === "ENOENT") {
      throw new ValidationError(
        `Traceback file not found: ${opts.tracebackPath}`,
        "traceback"
      );
    }
    throw new ValidationError(
      `Cannot read traceback file ${opts.tracebackPath}: ${(err as Error).message}`,
      "traceback"
    );
  }

  const { command, exitCode, frames } = parseTracebackContent(tracebackContent);

  // Enrich frames with source context
  await enrichFramesWithSourceContext(frames);

  // Reverse frames: traceback file is innermost-first, but Sentry expects
  // oldest-to-youngest (caller first, crash frame last).
  frames.reverse();

  // Parse log file breadcrumbs
  const breadcrumbs = opts.logPath
    ? await parseLogBreadcrumbs(opts.logPath)
    : undefined;

  // Get current username for the event
  let username: string | undefined;
  try {
    const { userInfo } = await import("node:os");
    username = userInfo().username;
  } catch (err) {
    log.debug("Could not determine username", err);
  }

  const environment = process.env.SENTRY_ENVIRONMENT || undefined;

  return {
    event_id: uuid4(),
    level: "error",
    platform: "other",
    timestamp: Date.now() / 1000,
    release: opts.release || undefined,
    environment,
    user: username ? { username, ip_address: "{{auto}}" } : undefined,
    tags:
      opts.tags && Object.keys(opts.tags).length > 0 ? opts.tags : undefined,
    breadcrumbs:
      breadcrumbs && breadcrumbs.length > 0 ? breadcrumbs : undefined,
    exception: {
      values: [
        {
          type: "BashError",
          value: `command ${command} exited with status ${exitCode}`,
          stacktrace: {
            frames,
          },
        },
      ],
    },
  };
}
