/**
 * Unit Tests for TRDIFF10 Binary Patch Application
 *
 * Note: Core invariants (offtin sign/magnitude, parsePatchHeader non-negative
 * values) are tested via property-based tests in bspatch.property.test.ts.
 * These tests focus on fixture-based patch application, negative-value rejection
 * (property generator clears sign bits), and error messages.
 *
 * Tests the bspatch implementation against real TRDIFF10 patches
 * generated by zig-bsdiff v0.1.19 (stored as test fixtures).
 */

import { createHash } from "node:crypto";
import { existsSync, unlinkSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { zstdCompressSync } from "node:zlib";
import {
  addDiffChunk,
  applyPatch,
  applyPatchChainInMemory,
  applyPatchToMemory,
  MAX_OUTPUT_SIZE,
  parsePatchHeader,
} from "binpatch";
import { describe, expect, test } from "vitest";

const FIXTURES_DIR = join(import.meta.dirname, "../fixtures/patches");

/**
 * Write a non-negative integer as a little-endian i64, matching the
 * sign-magnitude encoding that {@link offtin} reads (sign bit clear).
 */
function writeI64LE(buf: Uint8Array, offset: number, value: number): void {
  const view = new DataView(buf.buffer, buf.byteOffset + offset, 8);
  view.setUint32(0, value % 0x1_00_00_00_00, true);
  view.setUint32(4, Math.floor(value / 0x1_00_00_00_00), true);
}

/**
 * Build a minimal "diff-only" TRDIFF10 patch transforming `oldBytes` → `newBytes`
 * (which must be equal length). Emits one or more control tuples, each copying
 * up to `chunkSize` diff bytes (added to the old bytes), with no extra bytes and
 * no seek. Splitting into many small tuples forces the patcher to issue many
 * small windowed reads against the base — exercising {@link FileOldReader}'s
 * block cache across boundaries. Lets chain/cache tests run in CI without the
 * external zig-bsdiff encoder.
 *
 * @param chunkSize - Max diff bytes per control tuple (defaults to the whole file)
 */
function buildDiffOnlyPatch(
  oldBytes: Uint8Array,
  newBytes: Uint8Array,
  chunkSize = newBytes.length
): Uint8Array {
  if (oldBytes.length !== newBytes.length) {
    throw new Error("diff-only patch requires equal lengths");
  }
  const len = newBytes.length;

  // One control tuple per chunk: readDiffBy=chunk, readExtraBy=0, seekBy=0.
  const chunks: number[] = [];
  for (let remaining = len; remaining > 0; ) {
    const c = Math.min(chunkSize, remaining);
    chunks.push(c);
    remaining -= c;
  }
  const control = new Uint8Array(chunks.length * 24);
  for (let t = 0; t < chunks.length; t++) {
    writeI64LE(control, t * 24, chunks[t] ?? 0);
    writeI64LE(control, t * 24 + 8, 0);
    writeI64LE(control, t * 24 + 16, 0);
  }

  // diff[i] = (new[i] - old[i]) mod 256, so wrapping (old + diff) == new.
  const diff = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    diff[i] = ((newBytes[i] ?? 0) - (oldBytes[i] ?? 0) + 256) % 256;
  }

  const controlZ = new Uint8Array(zstdCompressSync(control));
  const diffZ = new Uint8Array(zstdCompressSync(diff));
  const extraZ = new Uint8Array(zstdCompressSync(new Uint8Array(0)));

  const patch = new Uint8Array(
    32 + controlZ.length + diffZ.length + extraZ.length
  );
  patch.set(new TextEncoder().encode("TRDIFF10"), 0);
  writeI64LE(patch, 8, controlZ.length);
  writeI64LE(patch, 16, diffZ.length);
  writeI64LE(patch, 24, len);
  patch.set(controlZ, 32);
  patch.set(diffZ, 32 + controlZ.length);
  patch.set(extraZ, 32 + controlZ.length + diffZ.length);
  return patch;
}

/**
 * Generate deterministic pseudo-random bytes via a 32-bit LCG. Uses modular
 * arithmetic (no bitwise ops) — intermediate products stay under 2^53.
 */
function makeBytes(seed: number, len: number): Uint8Array {
  const modulus = 0x1_00_00_00_00;
  const out = new Uint8Array(len);
  let x = seed % modulus;
  for (let i = 0; i < len; i++) {
    x = (x * 1_664_525 + 1_013_904_223) % modulus;
    out[i] = x % 256;
  }
  return out;
}

describe("parsePatchHeader: fixtures", () => {
  test("parses valid small fixture header", async () => {
    const patchData = new Uint8Array(
      await readFile(join(FIXTURES_DIR, "small.trdiff10"))
    );
    const header = parsePatchHeader(patchData);
    expect(header.controlLen).toBeGreaterThan(0);
    expect(header.diffLen).toBeGreaterThan(0);
    expect(header.newSize).toBe(54); // "Hello, World! This is the new file content. Version 2."
  });

  test("parses valid large fixture header", async () => {
    const patchData = new Uint8Array(
      await readFile(join(FIXTURES_DIR, "large.trdiff10"))
    );
    const header = parsePatchHeader(patchData);
    expect(header.controlLen).toBeGreaterThan(0);
    expect(header.diffLen).toBeGreaterThanOrEqual(0);
    expect(header.newSize).toBe(65_536);
  });

  test("rejects truncated patch (header claims more data than exists)", () => {
    const truncated = new Uint8Array(32);
    truncated.set(new TextEncoder().encode("TRDIFF10"));
    truncated[8] = 100; // controlLen = 100
    expect(() => parsePatchHeader(truncated)).toThrow("exceed file size");
  });

  test("rejects negative header values", () => {
    // Property generator clears sign bits (patched[15] %= 128) so never
    // exercises the negative-length error path — this test fills that gap
    const buf = new Uint8Array(64);
    buf.set(new TextEncoder().encode("TRDIFF10"));
    // offtin reads sign from bit 7 of byte 7 within each 8-byte field.
    // controlLen is at offset 8, so sign bit is byte 15.
    // Need non-zero magnitude + sign bit for a negative result.
    buf[8] = 1; // non-zero low byte → magnitude > 0
    buf[15] = 0x80; // Set sign bit → negative controlLen
    expect(() => parsePatchHeader(buf)).toThrow("negative");
  });

  test("rejects an attacker-controlled newSize above MAX_OUTPUT_SIZE", () => {
    // The header's newSize is used to preallocate the output buffer before the
    // patch content is verified. An unbounded value lets a malicious/corrupt
    // patch force an OOM via `new Uint8Array(newSize)` in applyReaderToMemory.
    // Regression test: a header claiming newSize > MAX_OUTPUT_SIZE must be
    // rejected here, before any allocation.
    const buf = new Uint8Array(64);
    buf.set(new TextEncoder().encode("TRDIFF10"));
    writeI64LE(buf, 8, 0); // controlLen = 0
    writeI64LE(buf, 16, 0); // diffLen = 0
    writeI64LE(buf, 24, MAX_OUTPUT_SIZE + 1); // newSize just over the cap
    expect(() => parsePatchHeader(buf)).toThrow("exceeds maximum");
  });

  test("accepts a newSize at MAX_OUTPUT_SIZE (boundary)", () => {
    const buf = new Uint8Array(64);
    buf.set(new TextEncoder().encode("TRDIFF10"));
    writeI64LE(buf, 8, 0);
    writeI64LE(buf, 16, 0);
    writeI64LE(buf, 24, MAX_OUTPUT_SIZE); // exactly the cap — allowed
    const header = parsePatchHeader(buf);
    expect(header.newSize).toBe(MAX_OUTPUT_SIZE);
  });
});

describe("applyPatch", () => {
  function tempFile(name: string): string {
    return join(tmpdir(), `bspatch-test-${Date.now()}-${name}`);
  }

  test("patches small text files correctly", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const patchData = new Uint8Array(
      await readFile(join(FIXTURES_DIR, "small.trdiff10"))
    );
    const destPath = tempFile("small-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);

      const expected = await readFile(join(FIXTURES_DIR, "small-new.bin"));
      const actual = await readFile(destPath);
      expect(new Uint8Array(actual)).toEqual(new Uint8Array(expected));

      const expectedHash = createHash("sha256").update(expected).digest("hex");
      expect(sha256).toBe(expectedHash);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("patches large binary files correctly", async () => {
    const oldPath = join(FIXTURES_DIR, "large-old.bin");
    const patchData = new Uint8Array(
      await readFile(join(FIXTURES_DIR, "large.trdiff10"))
    );
    const destPath = tempFile("large-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);

      const expected = await readFile(join(FIXTURES_DIR, "large-new.bin"));
      const actual = await readFile(destPath);
      expect(new Uint8Array(actual)).toEqual(new Uint8Array(expected));

      const expectedHash = createHash("sha256").update(expected).digest("hex");
      expect(sha256).toBe(expectedHash);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("returns correct SHA-256 hex digest", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const patchData = new Uint8Array(
      await readFile(join(FIXTURES_DIR, "small.trdiff10"))
    );
    const destPath = tempFile("sha256-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);
      expect(sha256).toMatch(/^[0-9a-f]{64}$/);
      expect(sha256.length).toBe(64);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("rejects non-TRDIFF10 magic", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const buf = new Uint8Array(64);
    buf.set(new TextEncoder().encode("BSDIFF40"));
    const destPath = tempFile("badmagic-out.bin");

    try {
      await expect(applyPatch(oldPath, buf, destPath)).rejects.toThrow(
        "Invalid patch format"
      );
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });
});

describe("applyPatchChainInMemory", () => {
  function tempFile(name: string): string {
    return join(
      tmpdir(),
      `bspatch-chain-${Date.now()}-${Math.random().toString(36).slice(2)}-${name}`
    );
  }

  test("applies a multi-hop chain in memory, writing only the final binary", async () => {
    // old --p1--> mid --p2--> new. The first hop reads the on-disk base via the
    // fd-backed reader; the second reads the in-memory intermediate. Exercises
    // both reader paths plus the chaining loop without touching scratch files.
    const oldBytes = makeBytes(1, 4096);
    const midBytes = makeBytes(2, 4096);
    const newBytes = makeBytes(3, 4096);
    const p1 = buildDiffOnlyPatch(oldBytes, midBytes);
    const p2 = buildDiffOnlyPatch(midBytes, newBytes);

    const oldPath = tempFile("old.bin");
    const destPath = tempFile("out.bin");
    await writeFile(oldPath, oldBytes);

    try {
      const sha256 = await applyPatchChainInMemory(oldPath, [p1, p2], destPath);

      const out = new Uint8Array(await readFile(destPath));
      expect(out).toEqual(newBytes);
      expect(sha256).toBe(createHash("sha256").update(newBytes).digest("hex"));

      // Intermediates are held in memory — no scratch files on disk.
      expect(existsSync(`${destPath}.patching.a`)).toBe(false);
      expect(existsSync(`${destPath}.patching.b`)).toBe(false);
    } finally {
      for (const p of [oldPath, destPath]) {
        if (existsSync(p)) {
          unlinkSync(p);
        }
      }
    }
  });

  test("onBytes reports every hop's output — total = sum of all newSizes", async () => {
    // The progress callback fires for the output bytes of EVERY hop (the
    // in-memory intermediate AND the final disk write), so a multi-hop total
    // must be the sum of all hops' newSize, not just the final binary's.
    // (Guards the delta-upgrade progress-bar total; a last-hop-only total
    // would freeze the bar at 100% after hop 1.)
    const oldBytes = makeBytes(1, 4096);
    const midBytes = makeBytes(2, 4096);
    const newBytes = makeBytes(3, 4096);
    const p1 = buildDiffOnlyPatch(oldBytes, midBytes);
    const p2 = buildDiffOnlyPatch(midBytes, newBytes);

    const oldPath = tempFile("old-ob.bin");
    const destPath = tempFile("out-ob.bin");
    await writeFile(oldPath, oldBytes);

    try {
      let reported = 0;
      await applyPatchChainInMemory(oldPath, [p1, p2], destPath, (n) => {
        reported += n;
      });
      // Two hops, each emitting 4096 output bytes.
      expect(reported).toBe(midBytes.length + newBytes.length);
    } finally {
      for (const p of [oldPath, destPath]) {
        if (existsSync(p)) {
          unlinkSync(p);
        }
      }
    }
  });

  test("single-element chain matches the on-disk patcher on a real fixture", async () => {
    // Exercises the fd-backed reader against a real zig-bsdiff patch whose
    // control entries include diff, extra, and seek operations.
    const oldPath = join(FIXTURES_DIR, "large-old.bin");
    const patchData = new Uint8Array(
      await readFile(join(FIXTURES_DIR, "large.trdiff10"))
    );
    const destPath = tempFile("single-chain.bin");

    try {
      const sha256 = await applyPatchChainInMemory(
        oldPath,
        [patchData],
        destPath
      );
      const expected = await readFile(join(FIXTURES_DIR, "large-new.bin"));
      expect(new Uint8Array(await readFile(destPath))).toEqual(
        new Uint8Array(expected)
      );
      expect(sha256).toBe(createHash("sha256").update(expected).digest("hex"));
    } finally {
      if (existsSync(destPath)) {
        unlinkSync(destPath);
      }
    }
  });

  test("rejects an empty patch chain", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const destPath = tempFile("empty-chain.bin");

    try {
      await expect(
        applyPatchChainInMemory(oldPath, [], destPath)
      ).rejects.toThrow("empty patch chain");
    } finally {
      if (existsSync(destPath)) {
        unlinkSync(destPath);
      }
    }
  });
});

describe("applyPatchToMemory", () => {
  function tempFile(name: string): string {
    return join(
      tmpdir(),
      `bspatch-mem-${Date.now()}-${Math.random().toString(36).slice(2)}-${name}`
    );
  }

  test("produces the same bytes and hash as the on-disk patcher", async () => {
    // Cross-checks the memory-backed reader against the fd-backed reader on a
    // real fixture patch (diff + extra + seek).
    const oldPath = join(FIXTURES_DIR, "large-old.bin");
    const oldBytes = new Uint8Array(await readFile(oldPath));
    const patchData = new Uint8Array(
      await readFile(join(FIXTURES_DIR, "large.trdiff10"))
    );
    const destPath = tempFile("disk.bin");

    try {
      const memOut = await applyPatchToMemory(oldBytes, patchData);
      const diskSha = await applyPatch(oldPath, patchData, destPath);
      const diskOut = new Uint8Array(await readFile(destPath));

      expect(memOut).toEqual(diskOut);
      expect(createHash("sha256").update(memOut).digest("hex")).toBe(diskSha);
    } finally {
      if (existsSync(destPath)) {
        unlinkSync(destPath);
      }
    }
  });
});

describe("addDiffChunk SWAR wrapping-add", () => {
  // The diff-add loop is the hot path of bspatch apply. The SWAR (Uint32Array)
  // implementation must match a per-byte `(old + diff) % 256` reference for
  // EVERY byte value, every 4-byte alignment, and every tail length 0-3 — a
  // carry bug (e.g. a BigUint64Array variant, where carries cross byte lanes)
  // corrupts the output silently.

  /** Per-byte wrapping-add reference (the specification addDiffChunk must meet). */
  function referenceAdd(old: Uint8Array, diff: Uint8Array): Uint8Array {
    const out = new Uint8Array(old.length);
    for (let i = 0; i < old.length; i++) {
      out[i] = ((old[i] ?? 0) + (diff[i] ?? 0)) % 256;
    }
    return out;
  }

  test("matches the byte-loop reference for all byte values and alignments", async () => {
    // Build a base covering many window sizes so every (old, diff) byte pair
    // appears across several 4-byte SWAR boundaries and tail lengths 0-3.
    // newBytes is derived from old+diff, so applyPatchToMemory must reproduce
    // exactly referenceAdd(old, diff).
    const total = 4096 + 3; // odd length hits a 3-byte tail
    const oldBytes = new Uint8Array(total);
    for (let i = 0; i < total; i++) {
      // Knuth multiplicative hash spread, folded to a byte — hits all 256 values.
      oldBytes[i] = Math.floor((i * 2_654_435_761) / 256) % 256;
    }
    // Vary the diff so (old, diff) pairs cover many high/low-bit combos.
    const diffBytes = new Uint8Array(total);
    for (let i = 0; i < total; i++) {
      diffBytes[i] = (i * 31 + (i % 256 >= 128 ? 128 : 0) + 7) % 256;
    }
    const expected = referenceAdd(oldBytes, diffBytes);
    const patch = buildDiffOnlyPatch(oldBytes, expected);

    const out = await applyPatchToMemory(oldBytes, patch);
    expect(out).toEqual(expected);
  });

  test("handles wrap-around at the byte max (255 + k) in every lane", async () => {
    // old=255 forces a carry in every byte; ensure it wraps to (255+diff)%256,
    // not into the adjacent lane. A cross-lane carry bug shows up here.
    const n = 64;
    const oldBytes = new Uint8Array(n).fill(0xff);
    const expected = new Uint8Array(n);
    for (let i = 0; i < n; i++) expected[i] = (0xff + i) % 256;
    const patch = buildDiffOnlyPatch(oldBytes, expected);

    const out = await applyPatchToMemory(oldBytes, patch);
    expect(out).toEqual(expected);
  });

  test("handles tail lengths 0-3 across many window sizes", async () => {
    for (const n of [1, 2, 3, 4, 5, 7, 8, 9, 21, 1023]) {
      const oldBytes = new Uint8Array(n);
      for (let i = 0; i < n; i++) oldBytes[i] = (i * 17) % 256;
      const expected = referenceAdd(
        oldBytes,
        Uint8Array.from({ length: n }, (_, i) => (i * 29) % 256)
      );
      const patch = buildDiffOnlyPatch(oldBytes, expected);
      const out = await applyPatchToMemory(oldBytes, patch);
      expect(out).toEqual(expected);
    }
  });

  test("produces correct output when a buffer view is misaligned (SWAR fallback)", () => {
    // The SWAR fast path needs a 4-byte-aligned byteOffset; addDiffChunk falls
    // back to the byte loop otherwise. No current caller passes a misaligned
    // view (MemoryOldReader/FileOldReader and the output chunk are all fresh,
    // offset-0 allocations), so this directly unit-tests the guard against a
    // future caller that might pass a pooled/subarray view. Every offset combo
    // (0-3 on each of old/diff/output) must match the per-byte reference.
    const n = 4096 + 3; // exercises a 3-byte tail too
    for (const oldOff of [0, 1, 2, 3]) {
      for (const diffOff of [0, 3]) {
        for (const outOff of [0, 2]) {
          const oldBuf = new Uint8Array(n + oldOff).subarray(oldOff);
          const diffBuf = new Uint8Array(n + diffOff).subarray(diffOff);
          const outBuf = new Uint8Array(n + outOff).subarray(outOff);
          for (let i = 0; i < n; i++) {
            oldBuf[i] = (i * 37) % 256;
            diffBuf[i] = (i * 53 + 3) % 256;
          }
          const expected = referenceAdd(oldBuf, diffBuf);
          addDiffChunk(outBuf, oldBuf, diffBuf, n);
          expect(outBuf).toEqual(expected);
        }
      }
    }
  });
});

describe("FileOldReader block cache", () => {
  const ONE_MIB = 1024 * 1024;

  function tempFile(name: string): string {
    return join(
      tmpdir(),
      `bspatch-cache-${Date.now()}-${Math.random().toString(36).slice(2)}-${name}`
    );
  }

  /** SHA-256 hex of `bytes`. */
  function sha(bytes: Uint8Array): string {
    return createHash("sha256").update(bytes).digest("hex");
  }

  /**
   * Apply `patch` to `oldBytes` via both the fd-backed reader (`applyPatch`,
   * which uses the block cache) and the in-memory reader (`applyPatchToMemory`,
   * cacheless), returning their result hashes plus `applyPatch`'s self-reported
   * hash. Any cache offset/staleness bug shows up as a hash divergence.
   *
   * Compares via SHA-256 rather than `toEqual` — Vitest's deep-equality is far
   * too slow on multi-MiB typed arrays (seconds per call), whereas native
   * hashing is O(n) and fast.
   */
  async function runBothReaders(
    oldBytes: Uint8Array,
    patch: Uint8Array
  ): Promise<{ fileSha: string; fileBytesSha: string; memSha: string }> {
    const oldPath = tempFile("old.bin");
    const destPath = tempFile("out.bin");
    await writeFile(oldPath, oldBytes);
    try {
      const fileSha = await applyPatch(oldPath, patch, destPath);
      const fileBytesSha = sha(new Uint8Array(await readFile(destPath)));
      const memSha = sha(await applyPatchToMemory(oldBytes, patch));
      return { fileSha, fileBytesSha, memSha };
    } finally {
      for (const p of [oldPath, destPath]) {
        if (existsSync(p)) {
          unlinkSync(p);
        }
      }
    }
  }

  test("serves many small windows spanning multiple blocks", async () => {
    // 3 MiB base read in ~100 KiB windows → reads cross the 1 MiB block
    // boundaries repeatedly, forcing several cache refills.
    const len = 3 * ONE_MIB + 12_345;
    const oldBytes = makeBytes(11, len);
    const newBytes = makeBytes(22, len);
    const patch = buildDiffOnlyPatch(oldBytes, newBytes, 100 * 1024);

    const expected = sha(newBytes);
    const { fileSha, fileBytesSha, memSha } = await runBothReaders(
      oldBytes,
      patch
    );
    expect(fileSha).toBe(expected);
    expect(fileBytesSha).toBe(expected);
    expect(memSha).toBe(expected);
  });

  test("reads a single window larger than the cache block", async () => {
    // One 1.5 MiB diff window > 1 MiB block → exercises the direct-read bypass.
    const len = ONE_MIB + ONE_MIB / 2;
    const oldBytes = makeBytes(33, len);
    const newBytes = makeBytes(44, len);
    const patch = buildDiffOnlyPatch(oldBytes, newBytes); // single tuple

    const expected = sha(newBytes);
    const { fileSha, fileBytesSha, memSha } = await runBothReaders(
      oldBytes,
      patch
    );
    expect(fileSha).toBe(expected);
    expect(fileBytesSha).toBe(expected);
    expect(memSha).toBe(expected);
  });

  test("handles windows landing exactly on a block boundary", async () => {
    // Window size divides the block size evenly, so a read lands precisely at
    // the 1 MiB boundary (start === blockStart + blockLen) — the off-by-one
    // boundary case for blockCovers.
    const len = 2 * ONE_MIB;
    const oldBytes = makeBytes(55, len);
    const newBytes = makeBytes(66, len);
    const patch = buildDiffOnlyPatch(oldBytes, newBytes, ONE_MIB / 4);

    const expected = sha(newBytes);
    const { fileSha, fileBytesSha, memSha } = await runBothReaders(
      oldBytes,
      patch
    );
    expect(fileSha).toBe(expected);
    expect(fileBytesSha).toBe(expected);
    expect(memSha).toBe(expected);
  });
});
