/**
 * Modern Sentry User Feedback types and output schemas.
 */

import type { EventAttachmentDetailsResponse } from "@sentry/api";
import { vEventAttachmentDetailsResponse } from "@sentry/api/valibot";
import {
  array,
  boolean,
  description,
  literal,
  looseObject,
  nullable,
  number,
  object,
  optional,
  pipe,
  string,
  unknown,
} from "valibot";
import type { SentryEvent, SentryIssue } from "./sentry.js";
import { SentryIssueSchema } from "./sentry.js";

/** Metadata stored on a modern Feedback issue group. */
export type FeedbackMetadata = {
  /** Feedback message submitted by the end user. */
  message: string;
  /** End-user email address, or null when omitted. */
  contact_email?: string | null;
  /** End-user display name, or null when omitted. */
  name?: string | null;
  /** Feedback title generated by Sentry. */
  title?: string;
  /** Search/display value generated by Sentry. */
  value?: string;
  /** Initial numeric priority assigned when the Feedback issue was created. */
  initial_priority?: number;
  /** Capture source such as `new_feedback_envelope`. */
  source?: string | null;
  /** AI-generated feedback summary, when available. */
  summary?: string | null;
  /** SDK that captured the feedback. */
  sdk?: {
    /** Raw SDK name. */
    name: string;
    /** Normalized SDK name used by Sentry. */
    name_normalized?: string;
  };
  /** Associated error event ID included by list responses. */
  associated_event_id?: string;
  /** Additional fields returned by newer Sentry versions. */
  [key: string]: unknown;
};

/** Modern User Feedback represented as a category-constrained Sentry issue. */
export type SentryFeedback = Omit<
  SentryIssue,
  "issueCategory" | "issueType" | "metadata"
> & {
  /** Discriminator for the issue category. */
  issueCategory: "feedback";
  /** Discriminator for the issue type. */
  issueType: "feedback";
  /** Feedback-specific issue metadata. */
  metadata: FeedbackMetadata;
  /** Whether the current user has read the feedback. */
  hasSeen?: boolean;
  /** Whether the latest event contains attachments. */
  latestEventHasAttachments?: boolean;
};

/** Data yielded by `feedback list` for human and JSON rendering. */
export type FeedbackListResult = {
  /** Feedback items on the current page. */
  feedback: SentryFeedback[];
  /** Whether a following page is available. */
  hasMore: boolean;
  /** Whether a previous page is available. */
  hasPrev: boolean;
  /** Server cursor for the following page. */
  nextCursor?: string | null;
  /** Resolved organization slug. */
  org: string;
  /** Resolved project slug, absent for organization-wide queries. */
  project?: string;
};

/** Data yielded by `feedback view` before JSON flattening. */
export type FeedbackViewResult = {
  /** Resolved organization slug, or null when unavailable. */
  org: string | null;
  /** The modern Feedback issue. */
  feedback: SentryFeedback;
  /** Latest event for the Feedback issue. */
  event: SentryEvent | null;
  /** Related Session Replay IDs. */
  replayIds: string[];
  /** Attachments on the latest Feedback event. */
  attachments: EventAttachmentDetailsResponse[];
};

/** Documentation schema for Feedback metadata. */
export const FeedbackMetadataSchema = pipe(
  looseObject({
    message: pipe(string(), description("Feedback message")),
    contact_email: optional(
      nullable(pipe(string(), description("End-user email address")))
    ),
    name: optional(
      nullable(pipe(string(), description("End-user display name")))
    ),
    title: optional(pipe(string(), description("Feedback title"))),
    value: optional(pipe(string(), description("Feedback display value"))),
    initial_priority: optional(
      pipe(
        number(),
        description("Initial priority assigned when the feedback was created")
      )
    ),
    source: optional(
      nullable(pipe(string(), description("Feedback capture source")))
    ),
    summary: optional(
      nullable(pipe(string(), description("AI-generated summary")))
    ),
    sdk: optional(
      pipe(
        object({
          name: pipe(string(), description("SDK name")),
          name_normalized: optional(
            pipe(string(), description("Normalized SDK name"))
          ),
        }),
        description("SDK that captured the feedback")
      )
    ),
    associated_event_id: optional(
      pipe(string(), description("Associated error event ID"))
    ),
  }),
  description("Feedback metadata")
);

/** Documentation schema for a modern Feedback issue. */
export const SentryFeedbackSchema = pipe(
  looseObject({
    ...SentryIssueSchema.entries,
    issueCategory: pipe(
      literal("feedback"),
      description("Issue category discriminator")
    ),
    issueType: pipe(
      literal("feedback"),
      description("Issue type discriminator")
    ),
    metadata: FeedbackMetadataSchema,
    hasSeen: optional(
      pipe(boolean(), description("Whether the feedback has been read"))
    ),
    latestEventHasAttachments: optional(
      pipe(boolean(), description("Whether the latest event has attachments"))
    ),
  }),
  description("Sentry User Feedback")
);

/** Documentation schema for flattened `feedback view` JSON output. */
export const FeedbackViewOutputSchema = pipe(
  looseObject({
    ...SentryFeedbackSchema.entries,
    org: pipe(nullable(string()), description("Organization slug")),
    event: pipe(nullable(unknown()), description("Latest feedback event")),
    replayIds: pipe(array(string()), description("Related Session Replay IDs")),
    attachments: pipe(
      array(vEventAttachmentDetailsResponse),
      description("Attachments on the latest feedback event")
    ),
  }),
  description("Feedback view output")
);
