#!/usr/bin/env tsx
/**
 * Generate Command Reference & Configuration Documentation
 *
 * Introspects the CLI's route tree and env var registry to generate
 * accurate reference pages for the documentation website. Flags, arguments,
 * aliases, and environment variables are extracted directly from source code,
 * preventing documentation drift.
 *
 * Each generated page combines:
 *   1. Auto-generated reference — from CLI metadata or env registry
 *   2. Hand-written fragment — examples, guides, tips (from docs/src/fragments/)
 *
 * The generated output is gitignored. Fragment files are the committed
 * source of truth for custom content.
 *
 * Usage:
 *   tsx script/generate-command-docs.ts
 *
 * Output:
 *   docs/src/content/docs/commands/{route}.md  (one per visible route)
 *   docs/src/content/docs/commands/index.md    (commands overview table)
 *   docs/src/content/docs/configuration.md     (env var reference + config fragment)
 */

import { mkdirSync, rmSync } from "node:fs";
import { access, readFile, writeFile } from "node:fs/promises";
import { DOCS_CONTENT, DOCS_FRAGMENTS } from "./paths.js";

// Ensure src/generated/skill-content.ts exists before importing the route tree.
// The route tree transitively imports agent-skills.ts → skill-content.ts, which
// is generated by generate:skill. On a fresh checkout (or CI without prior runs),
// the file won't exist yet. We create a minimal stub so the import resolves;
// generate:skill will overwrite it with real content afterward.
// Must run before the dynamic import below (static imports hoist above top-level await).
const SKILL_CONTENT_PATH = "src/generated/skill-content.ts";
const SKILL_CONTENT_STUB =
  "export const SKILL_FILES: [string, string][] = [];\n";
const skillContentExists = await access(SKILL_CONTENT_PATH).then(
  () => true,
  () => false
);
if (!skillContentExists) {
  mkdirSync("src/generated", { recursive: true });
  await writeFile(SKILL_CONTENT_PATH, SKILL_CONTENT_STUB);
}

import type { EnvVarEntry } from "../src/lib/env-registry.js";
import type {
  CommandInfo,
  FlagInfo,
  PositionalInfo,
  RouteInfo,
  RouteMap,
} from "../src/lib/introspect.js";

const { routes } = await import("../src/app.js");
const { extractAllRoutes } = await import("../src/lib/introspect.js");
const { ENV_VAR_REGISTRY } = await import("../src/lib/env-registry.js");

const DOCS_DIR = `${DOCS_CONTENT}/commands`;
const DOCS_CONTENT_DIR = DOCS_CONTENT;
const FRAGMENTS_DIR = `${DOCS_FRAGMENTS}/commands`;
const FRAGMENTS_ROOT = DOCS_FRAGMENTS;
const INDEX_PATH = `${DOCS_DIR}/index.md`;
const CONFIG_PATH = `${DOCS_CONTENT_DIR}/configuration.md`;

/**
 * Marker comment separating auto-generated reference content from
 * hand-written custom content. Everything above this line is regenerated;
 * everything below is preserved.
 */
const GENERATED_END_MARKER = "<!-- GENERATED:END -->";

/**
 * Flag names that are auto-injected by the buildCommand wrapper and
 * documented in the global footer rather than per-command.
 */
const GLOBAL_FLAG_NAMES = new Set([
  "json",
  "fields",
  "help",
  "helpAll",
  "log-level",
]);

/** Routes that don't need their own documentation page */
const SKIP_ROUTES = new Set(["help"]);

// ---------------------------------------------------------------------------
// Markdown Formatting
// ---------------------------------------------------------------------------

/**
 * Get visible, non-global flags for a command.
 * Excludes hidden flags and globally-injected flags (--json, --fields, etc.).
 */
function getVisibleFlags(cmd: CommandInfo): FlagInfo[] {
  return cmd.flags.filter((f) => !(f.hidden || GLOBAL_FLAG_NAMES.has(f.name)));
}

/**
 * Format a flag as a table row: `| -q, --query <query> | Search query ... |`
 *
 * Uses the flag name as the value placeholder for readability
 * (e.g., `--limit <limit>` instead of `--limit <value>`).
 */
function formatFlagRow(
  flag: FlagInfo,
  aliases: Record<string, string>
): string {
  const alias = Object.entries(aliases).find(([, v]) => v === flag.name)?.[0];

  let syntax = `--${flag.name}`;
  if (alias) {
    syntax = `-${alias}, ${syntax}`;
  }
  if ((flag.kind === "parsed" || flag.kind === "enum") && !flag.variadic) {
    syntax += ` <${flag.name}>`;
  } else if (flag.variadic) {
    syntax += ` <${flag.name}>...`;
  }

  let desc = flag.brief;
  // Only append default if the brief doesn't already mention it
  if (
    flag.default !== undefined &&
    flag.kind !== "boolean" &&
    !desc.includes("default:")
  ) {
    desc += ` (default: ${JSON.stringify(flag.default)})`;
  }

  return `| \`${syntax}\` | ${desc} |`;
}

/**
 * Escape angle brackets in text so they render as literal `<` / `>`
 * in HTML output rather than being interpreted as HTML tags.
 */
function escapeAngleBrackets(text: string): string {
  return text.replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Format positional arguments as a markdown table */
function formatPositionalsTable(positionals: PositionalInfo[]): string {
  if (positionals.length === 0) {
    return "";
  }

  const lines: string[] = [];
  lines.push("**Arguments:**");
  lines.push("");
  lines.push("| Argument | Description |");
  lines.push("|----------|-------------|");
  for (const p of positionals) {
    const placeholder = `\`<${p.placeholder}>\``;
    lines.push(`| ${placeholder} | ${escapeAngleBrackets(p.brief)} |`);
  }
  return lines.join("\n");
}

/** Format flags as a markdown options table */
function formatFlagsTable(
  flags: FlagInfo[],
  aliases: Record<string, string>
): string {
  if (flags.length === 0) {
    return "";
  }

  const lines: string[] = [];
  lines.push("**Options:**");
  lines.push("");
  lines.push("| Option | Description |");
  lines.push("|--------|-------------|");
  for (const flag of flags) {
    lines.push(formatFlagRow(flag, aliases));
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Page Generation
// ---------------------------------------------------------------------------

/** Generate the auto-generated reference section for a single command */
function generateCommandSection(cmd: CommandInfo): string {
  const lines: string[] = [];

  // Command heading
  const signature = cmd.positional ? `${cmd.path} ${cmd.positional}` : cmd.path;
  lines.push(`### \`${signature}\``);
  lines.push("");
  lines.push(cmd.brief);

  // Arguments table
  if (cmd.positionals.length > 0) {
    lines.push("");
    lines.push(formatPositionalsTable(cmd.positionals));
  }

  // Options table
  const visibleFlags = getVisibleFlags(cmd);
  if (visibleFlags.length > 0) {
    lines.push("");
    lines.push(formatFlagsTable(visibleFlags, cmd.aliases));
  }

  return lines.join("\n");
}

/** Determine if a route is a standalone command (not a group with subcommands) */
function isStandaloneCommand(route: RouteInfo): boolean {
  return (
    route.commands.length === 1 &&
    route.commands[0].path === `sentry ${route.name}`
  );
}

/**
 * Generate the full auto-generated portion of a command doc page.
 *
 * Includes frontmatter, intro, per-command reference sections,
 * and the global flags footer.
 */
function generatePage(route: RouteInfo): string {
  const standalone = isStandaloneCommand(route);
  const description = standalone
    ? `${capitalize(route.name)} command for the Sentry CLI`
    : `${capitalize(route.name)} commands for the Sentry CLI`;

  const lines: string[] = [];

  // YAML frontmatter
  lines.push("---");
  lines.push(`title: ${route.name}`);
  lines.push(`description: ${description}`);
  lines.push("---");
  lines.push("");

  // Intro
  lines.push(route.brief);
  lines.push("");

  // Section heading
  lines.push(standalone ? "## Usage" : "## Commands");
  lines.push("");

  // Per-command sections
  for (const cmd of route.commands) {
    lines.push(generateCommandSection(cmd));
    lines.push("");
  }

  // Global flags footer
  lines.push(
    "All commands support `--json` for machine-readable output and `--fields` to select specific JSON fields."
  );
  lines.push("");

  // End marker
  lines.push(GENERATED_END_MARKER);

  return lines.join("\n");
}

/** Known acronyms that should be fully uppercased in titles */
const ACRONYMS = new Set(["api", "cli"]);

function capitalize(s: string): string {
  if (ACRONYMS.has(s)) {
    return s.toUpperCase();
  }
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Index Table Generation
// ---------------------------------------------------------------------------

/**
 * Generate the commands table for index.md.
 * Uses the route order from extractAllRoutes() (which preserves the
 * insertion order from app.ts's buildRouteMap) — no manual constant needed.
 */
function generateCommandsTable(allRoutes: RouteInfo[]): string {
  const lines: string[] = [];
  lines.push("| Command | Description |");
  lines.push("|---------|-------------|");
  for (const route of allRoutes) {
    lines.push(`| [\`${route.name}\`](./${route.name}/) | ${route.brief} |`);
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Configuration Page Generation
// ---------------------------------------------------------------------------

/**
 * Generate a `### \`VAR_NAME\`` section for a single environment variable.
 * Matches the existing hand-written format in configuration.md.
 */
function generateEnvVarSection(entry: EnvVarEntry): string {
  const lines: string[] = [];
  lines.push(`### \`${entry.name}\``);
  lines.push("");
  lines.push(entry.description);

  if (entry.example !== undefined) {
    lines.push("");
    lines.push("```bash");
    lines.push(`export ${entry.name}=${entry.example}`);
    lines.push("```");
  }

  return lines.join("\n");
}

/**
 * Generate the full auto-generated portion of the configuration page.
 *
 * Includes frontmatter, intro paragraph, and per-variable reference
 * sections. The fragment (config file docs, global options, credential
 * storage) is appended after the end marker.
 */
function generateConfigurationPage(registry: readonly EnvVarEntry[]): string {
  const lines: string[] = [];

  // YAML frontmatter
  lines.push("---");
  lines.push("title: Configuration");
  lines.push(
    "description: Environment variables, config files, and configuration options for the Sentry CLI"
  );
  lines.push("---");
  lines.push("");

  // Intro
  lines.push(
    "The Sentry CLI can be configured through config files, environment variables, and a local database. Most users don't need to set any of these — the CLI auto-detects your project from your codebase and stores credentials locally after `sentry auth login`."
  );
  lines.push("");

  // Environment Variables section
  lines.push("## Environment Variables");
  lines.push("");

  for (const entry of registry) {
    lines.push(generateEnvVarSection(entry));
    lines.push("");
  }

  // End marker
  lines.push(GENERATED_END_MARKER);

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Custom Content (Fragment Files)
// ---------------------------------------------------------------------------

/**
 * Read hand-written custom content from a command fragment file.
 * Fragment files live in docs/src/fragments/commands/ and contain only
 * the custom sections (examples, guides) — no frontmatter or generated content.
 * Returns empty string if the fragment file doesn't exist.
 */
async function readCustomContent(fragmentName: string): Promise<string> {
  try {
    return await readFile(`${FRAGMENTS_DIR}/${fragmentName}.md`, "utf-8");
  } catch {
    return "";
  }
}

/**
 * Read hand-written custom content from a top-level fragment file.
 * Top-level fragments live in docs/src/fragments/ (not the commands/ subdirectory).
 * Returns empty string if the fragment file doesn't exist.
 */
async function readTopLevelFragment(fragmentName: string): Promise<string> {
  try {
    return await readFile(`${FRAGMENTS_ROOT}/${fragmentName}.md`, "utf-8");
  } catch {
    return "";
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const routeMap = routes as unknown as RouteMap;
const routeInfos = extractAllRoutes(routeMap).filter(
  (r) => !SKIP_ROUTES.has(r.name)
);

const generatedFiles: string[] = [];

// Ensure output directory exists (it's gitignored, may be absent on fresh checkout)
mkdirSync(DOCS_DIR, { recursive: true });

// Clean up legacy cli/ subdirectory if it exists (we now use cli.md)
try {
  rmSync(`${DOCS_DIR}/cli`, { recursive: true, force: true });
} catch {
  // Directory may not exist
}

// Generate command doc pages
for (const route of routeInfos) {
  const filePath = `${DOCS_DIR}/${route.name}.md`;
  const pageContent = generatePage(route);
  const customContent = await readCustomContent(route.name);
  const fullContent = customContent
    ? pageContent + customContent
    : `${pageContent}\n`;

  await writeFile(filePath, fullContent);
  generatedFiles.push(filePath);
}

// Update commands/index.md
const indexCustomContent = await readCustomContent("index");
const indexLines: string[] = [];
indexLines.push("---");
indexLines.push("title: Commands");
indexLines.push("description: Available commands in the Sentry CLI");
indexLines.push("---");
indexLines.push("");
indexLines.push(
  "The Sentry CLI provides commands for interacting with various Sentry resources."
);
indexLines.push("");
indexLines.push("## Available Commands");
indexLines.push("");
indexLines.push(generateCommandsTable(routeInfos));
indexLines.push("");
indexLines.push(GENERATED_END_MARKER);

const indexContent = indexCustomContent
  ? indexLines.join("\n") + indexCustomContent
  : `${indexLines.join("\n")}\n`;

await writeFile(INDEX_PATH, indexContent);

// ---------------------------------------------------------------------------
// Generate configuration.md (env var reference + fragment)
// ---------------------------------------------------------------------------

const configGenerated = generateConfigurationPage(ENV_VAR_REGISTRY);
const configFragment = await readTopLevelFragment("configuration");
const configContent = configFragment
  ? configGenerated + configFragment
  : `${configGenerated}\n`;

await writeFile(CONFIG_PATH, configContent);

console.log(
  `Generated ${generatedFiles.length} command doc pages + ${INDEX_PATH} + ${CONFIG_PATH}`
);
