#!/usr/bin/env tsx
/**
 * Generate Search Query Parser from PEG Grammar
 *
 * Uses Peggy to compile the simplified Sentry search query grammar
 * into a standalone ES module parser. The generated parser is used
 * by `src/lib/search-query.ts` for structural query classification
 * (OR→in-list rewriting, AND stripping, paren group handling).
 *
 * The grammar is a simplified version of Sentry's canonical PEG grammar:
 *   https://github.com/getsentry/sentry/blob/master/static/app/components/searchSyntax/grammar.pegjs
 *
 * Usage:
 *   tsx script/generate-parser.ts
 *
 * Output:
 *   src/generated/search-parser.js   — the generated parser (ES module)
 *   src/generated/search-parser.d.ts — TypeScript type declarations
 */

import { mkdirSync } from "node:fs";
import { readFile, stat, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import peggy from "peggy";

const GRAMMAR_PATH = resolve("script/search-query.pegjs");
const OUTPUT_JS = resolve("src/generated/search-parser.js");
const OUTPUT_DTS = resolve("src/generated/search-parser.d.ts");

const HEADER = "// Auto-generated by script/generate-parser.ts — DO NOT EDIT\n";

// Read the PEG grammar source
const grammarSource = await readFile(GRAMMAR_PATH, "utf-8");

// Compile to JavaScript source
const parserSource = peggy.generate(grammarSource, {
  output: "source",
  format: "es",
  allowedStartRules: ["search"],
});

// Ensure output directory exists
mkdirSync(dirname(OUTPUT_JS), { recursive: true });

// Write the generated parser
await writeFile(OUTPUT_JS, `${HEADER}\n${parserSource}\n`);

// Write TypeScript declarations
const dts = `${HEADER}
/** A text filter: key:value */
export type TextFilter = {
  type: "text_filter";
  negated: boolean;
  key: string;
  value: string;
};

/** An in-list filter: key:[val1,val2] */
export type TextInFilter = {
  type: "text_in_filter";
  negated: boolean;
  key: string;
  values: string[];
};

/** A comparison filter: key:>value, key:<=value */
export type ComparisonFilter = {
  type: "comparison_filter";
  negated: boolean;
  key: string;
  op: string;
  value: string;
};

/** Free text (no key: prefix) */
export type FreeText = {
  type: "free_text";
  value: string;
  quoted: boolean;
};

/** A boolean operator (AND / OR) */
export type BooleanOp = {
  type: "boolean_op";
  op: "AND" | "OR";
};

/** A parenthesized group */
export type ParenGroup = {
  type: "paren_group";
  inner: SearchNode[];
  raw: string;
};

/** Union of all search query AST node types. */
export type SearchNode =
  | TextFilter
  | TextInFilter
  | ComparisonFilter
  | FreeText
  | BooleanOp
  | ParenGroup;

/** Parse a Sentry search query into an AST node list. */
export function parse(input: string): SearchNode[];
`;

await writeFile(OUTPUT_DTS, dts);

const jsSize = ((await stat(OUTPUT_JS)).size / 1024).toFixed(1);
console.log(`Generated ${OUTPUT_JS} (${jsSize} KB)`);
console.log(`Generated ${OUTPUT_DTS}`);
