/**
 * Hand-written half of the published type declarations (`dist/index.d.cts` / `.d.mts`).
 *
 * The per-command `SentrySDK` types are generated by `generate-sdk.ts`; everything here
 * describes the library entry point itself.
 */

/** Location of the module `SentryOptions` is lifted from, relative to `packages/cli`. */
export const SDK_TYPES_PATH = "src/lib/sdk-types.ts";

const SENTRY_OPTIONS_START = /export type SentryOptions = \{/m;
const SENTRY_OPTIONS_END = /^\}\s*;/;

/**
 * Lifts the `SentryOptions` declaration verbatim out of `sdk-types.ts`.
 *
 * This used to be a hand-written copy, which drifted without anything failing: `headers` was
 * added to the source and worked at runtime in 0.44.0, yet consumers passing it got a type
 * error because the copy never learned about the option.
 */
export function extractSentryOptions(sdkTypesSource: string): string {
  const startMatch = sdkTypesSource.match(SENTRY_OPTIONS_START);
  if (!startMatch || startMatch.index === undefined) {
    throw new Error(
      `Could not find the \`SentryOptions\` declaration in ${SDK_TYPES_PATH}.`
    );
  }

  const start = startMatch.index;
  let depth = 1;
  let i = start + startMatch[0].length;
  while (i < sdkTypesSource.length && depth > 0) {
    const char = sdkTypesSource[i];
    if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;
    }
    i += 1;
  }

  const endMatch = sdkTypesSource.slice(i - 1).match(SENTRY_OPTIONS_END);
  if (depth !== 0 || !endMatch) {
    throw new Error(
      `Could not find the \`SentryOptions\` declaration in ${SDK_TYPES_PATH}.`
    );
  }

  return sdkTypesSource.slice(start, i - 1 + endMatch[0].length);
}

/** Assembles the entry-point declarations from the current `sdk-types.ts` source. */
export function buildCoreDeclarations(sdkTypesSource: string): string {
  return `${extractSentryOptions(sdkTypesSource)}

export type AsyncChannel<T> = AsyncIterable<T> & {
  push(value: T): void;
  close(): void;
  error(err: Error): void;
};

export declare class SentryError extends Error {
  readonly exitCode: number;
  readonly stderr: string;
  constructor(message: string, exitCode: number, stderr: string);
}

export declare function createSentrySDK(options?: SentryOptions): SentrySDK & {
  /** Run an arbitrary CLI command (escape hatch). Streaming flags return AsyncIterable. */
  run(...args: string[]): Promise<unknown> | AsyncIterable<unknown>;
};

export default createSentrySDK;
`;
}
